platform :ios, '8.0'
use_frameworks!

target 'DelegateIt' do
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Socket.IO-Client-Swift', '~> 4.1.6' # Or latest version
  pod 'JSQMessagesViewController' 
  pod 'Stripe'
  pod 'CWStatusBarNotification', '~> 2.3.3'
end
